"""atualizando o banco de dados para o gravatar

Revision ID: 3629a50bfe3f
Revises: a2166392ee8d
Create Date: 2021-09-26 21:12:00.619664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3629a50bfe3f'
down_revision = 'a2166392ee8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
